export const UPDATE_CURRENT_ICON_SHIFT = 'UPDATE_CURRENT_ICON_SHIFT';
export const UPDATE_CURRENT_SNAPPED_ICON = 'UPDATE_CURRENT_SNAPPED_ICON';
export const SET_PATH_RADIUS_AND_COORDINATES = 'SET_PATH_RADIUS_AND_COORDINATES';
export const HIDE_ICON = 'HIDE_ICON';
export const SHOW_ICON = 'SHOW_ICON';
export const HIDE_ARROW_HINT = 'HIDE_ARROW_HINT';
