export const UPDATE_CURRENT_ICON_SHIFT_AND_GESTURE_VX = 'UPDATE_CURRENT_ICON_SHIFT_AND_GESTURE_VX';
export const UPDATE_CURRENT_SNAPPED_ICON_AND_SHIFT = 'UPDATE_CURRENT_SNAPPED_ICON_AND_SHIFT';
export const SET_PATH_RADIUS_AND_COORDINATES = 'SET_PATH_RADIUS_AND_COORDINATES';
export const HIDE_ICON = 'HIDE_ICON';
export const SHOW_ICON = 'SHOW_ICON';
export const HIDE_ARROW_HINT = 'HIDE_ARROW_HINT';
